### ISSUE TITLE
Longer text inside the snackbar is cut off

### ISSUE THREAD

**Issue by vgavrilovikj** [GiYeongUM/flutter_icon_snackbar#1]
Is there any option to properly handle and support longer text inside the IconSnackbar. When I receive a longer text from the backend such as "The reservation has been successfully approved" the text is cut off and does not show the full text. How can I add support for multi-line text?

View image below as reference:
![image](https://github.com/GiYeongUM/flutter_icon_snackbar/assets/29601489/82e59af0-4227-42fb-99db-e5b8f4bfebb9)

**Comment by GiYeongUM** [comment]
@vgavrilovikj  I will proceed with solving the problem! Thank you for your opinion!

**Comment by GiYeongUM** [comment]
Issue fixed on v1.1.5 Thanks!

**Comment by vgavrilovikj** [comment]
Thanks a lot! Could you please add '...' in case the text is longer and it takes more than 2 lines, like on the image below:
![image](https://github.com/GiYeongUM/flutter_icon_snackbar/assets/29601489/6b79ed9e-33b0-488b-9289-2c3f0d6f4d61)

**Comment by GiYeongUM** [comment]
@vgavrilovikj no problem! I added the maxlines option to SnackBarStyle in version 1.1.6 and Textoverflow set it to elipsis to update!

**Comment by vgavrilovikj** [comment]
Thanks a lot!
