### ISSUE TITLE
SnackBar push FloatingActionButton upward

### ISSUE THREAD

**Issue by MDeLuise** [GiYeongUM/flutter_icon_snackbar#2]
Hi!
## Description:
When using the FloatingActionButton along with a SnackBar, I noticed that when the SnackBar is displayed, it pushes the FloatingActionButton upward, which can be visually disruptive. It would be helpful to have an option to prevent this behavior.

## Proposed Solution:
I believe that setting the `behavior` of the SnackBar to `floating` [could potentially resolve this issue](https://stackoverflow.com/a/58830385/20088695). This way, the SnackBar would overlay on top of other UI elements without affecting their layout.

## Video recording
https://github.com/GiYeongUM/flutter_icon_snackbar/assets/66636702/8773fdb2-30fe-4714-bbcf-d75b1fba354f

**Comment by GiYeongUM** [comment]
@MDeLuise Hi! I checked your issue content, I will revise and reflect it! BRB.

**Comment by GiYeongUM** [comment]
@MDeLuise I added the SnackBarBehavior option in version 1.1.7 The default value is fixed option, and I modified it to make floating available as well. Thank you so much for your comments.

**Comment by MDeLuise** [comment]
Great, thanks so much!
