### ISSUE TITLE
iconColor in SnackBarStyle does not take effect

### ISSUE THREAD

**Issue by yanashenyang** [GiYeongUM/flutter_icon_snackbar#3]
iconColor in SnackBarStyle does not take effect
Because your source code does not use this iconColor at all

<img width="749" alt="image" src="https://github.com/user-attachments/assets/9e46bf93-bbc9-41e9-a04b-fabc74e4ffab">

**Comment by yanashenyang** [comment]
Don't you test it?

**Comment by GiYeongUM** [comment]
@yanashevenyang modified the snack bar style option in version 1.2.0. Thank you for your comments.
